name: Documentation Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 🎩 Install Bundler
        run: |
          sudo gem update --system
          sudo gem install bundler -v 1.17.2
          sudo bundle install --gemfile=docs/Gemfile
      - name: Build
        run: ./tools/ci/docs.sh