name: Documentation Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: 🎩 Install Jekyll
        run: |
          sudo gem update --system
          sudo bundle install
      - name: Build
        run: ./tools/ci/docs.sh